# Generated by Django 4.2.7 on 2023-12-11 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mymailbox.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mymailbox', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usericon',
            name='email',
        ),
        migrations.AddField(
            model_name='usericon',
            name='user',
            field=models.OneToOneField(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usericon',
            name='icon',
            field=models.ImageField(default='icons/default_icon.png', upload_to=mymailbox.models.user_icon_upload_to),
        ),
    ]
