# Generated by Django 4.2.7 on 2023-12-14 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mymailbox.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mymailbox', '0002_remove_usericon_email_usericon_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_starred_by_sender', models.BooleanField(default=False)),
                ('is_starred_by_recipient', models.BooleanField(default=False)),
                ('is_trashed_by_recipient', models.BooleanField(default=False)),
                ('is_trashed_by_sender', models.BooleanField(default=False)),
                ('is_deleted_by_recipient', models.BooleanField(default=False)),
                ('is_deleted_by_sender', models.BooleanField(default=False)),
                ('files', models.FileField(blank=True, null=True, upload_to=mymailbox.models.message_upload_to)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-sent_at',),
            },
        ),
    ]
