# Generated by Django 4.2.7 on 2023-12-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymailbox', '0004_rename_files_message_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
